### ISSUE TITLE
Arg order of `shutit.login`

### ISSUE THREAD

**Issue by aidanhs** [ianmiell/shutit#165]
2bfb783eb14557449eb changed this. How often do you find yourself needing to change the command you use to login with?

**Comment by aidanhs** [comment]
:(

**Comment by ianmiell** [comment]
Oh I thought you'd committed it already?

**Comment by ianmiell** [comment]
Actually, surprisingly often!
But I agree the ordering should be reversed from that commit.

**Comment by aidanhs** [comment]
Interesting, how do you use it? If there's a reason then we can just leave it and I'll fix where it's a problem.

**Comment by ianmiell** [comment]
Nope, agree with your ordering - in fact, that reversal caused me a few problems due to the 

I've had systems without su (believe it or not).

[imiell@alberti /space/git/shutit-distro]$ grep -rnw shutit.login *
google_compute/google_compute.py:14:		shutit.login(command='bash')
qt4/qt4.py:24:		shutit.login(command='bash -e')
x7proto/x7proto.py:19:		shutit.login(command='bash -e')
xorg_apps/xorg_apps.py:16:		shutit.login(command='bash -e')
xorg_libs/xorg_libs.py:17:		shutit.login(command='bash -e')
[imiell@alberti /space/git/shutit-distro]$ 

but the default case will be user as you suggest.
