### ISSUE TITLE
[question] Different py files in module dir

### ISSUE THREAD

**Issue by marcelloromani** [ianmiell/shutit#170]
Say I have created a module and end up having multiple .py in the module's directory. How are they treated by a call to `shutit build`?
Is one-py-file-per-module a recommended practice?

**Comment by ianmiell** [comment]
You can have multiple .py files per module, sure.

By convention, the config/build.cnf file should indicate which of these
will be built "by default".

Perhaps you have differently-nuanced examples of a similar module that are
non-standard but available to mark as built. Or you have optional build
steps that go with a module (like a special "debug" setup only built on
request that installs all sorts of weird stuff).

In these cases it makes sense to bundle the py files together rather than
separate them inconveniently in different folders.

**Comment by marcelloromani** [comment]
So each file will declare a different module_id, and unless it's required as dependency from other to-be-built modules (e.g. the default one specified in configs/build.cnf), it won't be touched by shiutit build. Is that correct? (I might try experiment myself...)

**Comment by marcelloromani** [comment]
If I understood correcly, `configs/build.cnf`(*) must contain the following:
```
[<module_id>]
shutit.core.module.build: yes
```
for each `<module_id>` we want to be built.

(*) or any config file in the config chain.

**Comment by ianmiell** [comment]
Yes, if you want it to be included by default.
You can also add them at the command line with "-s <module id> build yes"
